### PR TITLE
Send AWS SDK metrics to CloudWatch

### PR DESCRIPTION
**Pull request by joelochlann**
# The problem
In the past we've had Giant incidents caused by exhaustion of the S3 connection pool.

We've tried to mitigate by closing input streams (https://github.com/guardian/pfi/pull/924, #11) but they still crop up sometimes during large ingestions when the workers have lots of connections to S3.

The new page viewer (#32) has made this more common because it also makes lots of requests to S3 for individual pages.

# The solution
We want to get visibility on when we're in danger of hitting this issue. AWS provides extra metrics from its Java SDK, including around connection pools to AWS services such as S3, but you need to do some special stuff to enable it.

You can apparently do it by calling some methods on `AwsSdkMetrics`:
https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/

Or by setting some JVM options:
https://aws.amazon.com/blogs/developer/enabling-metrics-with-the-aws-sdk-for-java/

What neither of those tell you is **you need an extra dependency for it to work**:

```scala
"com.amazonaws" % "aws-java-sdk-cloudwatchmetrics" % awsVersion
```

# How they appear in CloudWatch
By default, they appear under custom namespaces formed from the stack/app/stage tags (no idea how AWS knows by default to use these... thought they were a Guardian-specific convention?)

If this is unhelpful I think we can customise. I haven't really played with CloudWatch metrics enough to know what makes the most sense

## top-level
Screzenshot 2022-08-11 at 12 50 59

## > pfi-playground-rex
Some useful JVM stuff in these other categories, e.g. heap space, number of threads, etc
Screenshot 2022-08-11 at 12 51 06

## > pfi-playground-rex > Metric Type
for some reason the connection pool metrics come under this generic "Metric Type" heading
Screenshot 2022-08-11 at 12 51 33

### CODE REVIEW

**Comment by joelochlann** [comment]
## todo
- [ ] tell AWS about the missing bit in their docs (the `cloudwatchmetrics` dependency)
- [ ] create a departmental recommendation

**Comment by philmcmahon** [comment]
Nice one Joe!

With my eternal cost hat on, cloudwatch metrics are $3.60/year/metric - so this will work out around $500/year for playground, I imagine similar for prod. Definitely cheaper than spending hours guessing where we're exhausting our connection pool but worth thinking about.

**Comment by philmcmahon** [comment]
> ## todo
> 
>     * [ ]  tell AWS about the missing bit in their docs (the `cloudwatchmetrics` dependency)
> 
>     * [ ]  create a departmental recommendation

I think the departmental recommendation should come with a cost warning

**Review by philmcmahon — APPROVED** [review]

**Comment by joelochlann** [comment]
great points about cost!

**Comment by joelochlann** [comment]
I'll wait to see if there's any feedback in Eng channel before posting recommendation

**Pull request merged**
